name: Prettier

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Run Prettier
        run: yarn format -- --check
      - name: Check Prettier Results
        run: |
          if git diff-index --quiet HEAD --; then
            echo "Prettier check passed"
          else
            echo "Prettier check failed. Please run 'npm run format' to format your code."
            exit 1
          fi
